logging:
  level:
    '[root]': WARN
    '[com.leaf]': INFO
    '[org.springframework]': WARN

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/file}

cloudinary:
  url: ${CLOUDINARY_URL}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:12345678}
  bucket: ${MINIO_BUCKET_NAME:leaf-bucket}
