import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import localFont from 'next/font/local';
import './globals.css';
import AppLayout from '@/views/layouts/AppLayout';

const nunito = localFont({
  src: [
    { path: '../public/fonts/Nunito-ExtraLight.ttf', weight: '200', style: 'normal' },
    { path: '../public/fonts/Nunito-ExtraLightItalic.ttf', weight: '200', style: 'italic' },
    { path: '../public/fonts/Nunito-Light.ttf', weight: '300', style: 'normal' },
    { path: '../public/fonts/Nunito-LightItalic.ttf', weight: '300', style: 'italic' },
    { path: '../public/fonts/Nunito-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../public/fonts/Nunito-Italic.ttf', weight: '400', style: 'italic' },
    { path: '../public/fonts/Nunito-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../public/fonts/Nunito-MediumItalic.ttf', weight: '500', style: 'italic' },
    { path: '../public/fonts/Nunito-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '../public/fonts/Nunito-SemiBoldItalic.ttf', weight: '600', style: 'italic' },
    { path: '../public/fonts/Nunito-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../public/fonts/Nunito-BoldItalic.ttf', weight: '700', style: 'italic' },
    { path: '../public/fonts/Nunito-ExtraBold.ttf', weight: '800', style: 'normal' },
    { path: '../public/fonts/Nunito-ExtraBoldItalic.ttf', weight: '800', style: 'italic' },
    { path: '../public/fonts/Nunito-Black.ttf', weight: '900', style: 'normal' },
    { path: '../public/fonts/Nunito-BlackItalic.ttf', weight: '900', style: 'italic' },
  ],
  display: 'swap',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getInitialLanguage = async () => {
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get('language')?.value;
  return cookieLang === 'en' ? 'en' : 'vi';
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialLanguage = await getInitialLanguage();

  return (
    <html lang={initialLanguage} suppressHydrationWarning>
      <head />
      <body className={`${nunito.variable} antialiased`} suppressHydrationWarning>
        <AppLayout initialLanguage={initialLanguage}>{children}</AppLayout>
      </body>
    </html>
  );
}
