server:
  servlet:
    context-path: /posts
  port: 1004

grpc:
  server:
    port: 9004

spring:
  application:
    name: posts

  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
