version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_canhtv05
    restart: always
    environment:
      POSTGRES_USER: canhtv05
      POSTGRES_PASSWORD: canhtv05
      POSTGRES_DB: canhtv05
    ports:
      - "5432:5432"
    volumes:
      - postgres_canhtv05:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:latest
    container_name: redis_canhtv05
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_canhtv05:/data

volumes:
  postgres_canhtv05:
  redis_canhtv05:
