export enum Viewport {
  '2XL' = 1536,
  XL = 1280,
  LG = 1024,
  MD = 768,
  SM = 640,
}

export enum Status {
  UNAUTHENTICATED = 'status.unauthenticated',
  UPDATE_SUCCESS = 'status.update_success',
  UPDATE_FAILED = 'status.update_failed',
  ADD_SUCCESS = 'status.add_success',
  ADD_FAILED = 'status.add_failed',
  REMOVE_SUCCESS = 'status.remove_success',
  REMOVE_FAILED = 'status.remove_failed',
  ERROR = 'status.error',
}

export enum PrivacyLevel {
  PRIVACY_LEVEL_PUBLIC = 'PRIVACY_LEVEL_PUBLIC',
  PRIVACY_LEVEL_PRIVATE = 'PRIVACY_LEVEL_PRIVATE',
  PRIVACY_LEVEL_CUSTOM = 'PRIVACY_LEVEL_CUSTOM',
  PRIVACY_LEVEL_FRIENDS_ONLY = 'PRIVACY_LEVEL_FRIENDS_ONLY',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  INVALID = 'INVALID',
  EXPIRED = 'EXPIRED',
}

export enum Gender {
  GENDER_UNSPECIFIED = 'GENDER_UNSPECIFIED',
  GENDER_MALE = 'GENDER_MALE',
  GENDER_FEMALE = 'GENDER_FEMALE',
  GENDER_OTHER = 'GENDER_OTHER',
}

export enum RelationshipStatus {
  RELATIONSHIP_STATUS_UNSPECIFIED = 'RELATIONSHIP_STATUS_UNSPECIFIED', // Mặc định
  RELATIONSHIP_STATUS_SINGLE = 'RELATIONSHIP_STATUS_SINGLE',
  RELATIONSHIP_STATUS_IN_A_RELATIONSHIP = 'RELATIONSHIP_STATUS_IN_A_RELATIONSHIP',
  RELATIONSHIP_STATUS_ENGAGED = 'RELATIONSHIP_STATUS_ENGAGED',
  RELATIONSHIP_STATUS_MARRIED = 'RELATIONSHIP_STATUS_MARRIED',
  RELATIONSHIP_STATUS_ITS_COMPLICATED = 'RELATIONSHIP_STATUS_ITS_COMPLICATED', // Đã bỏ dấu ' và viết hoa
  RELATIONSHIP_STATUS_IN_LOVE = 'RELATIONSHIP_STATUS_IN_LOVE', // "Đang yêu"
  RELATIONSHIP_STATUS_WIDOWED = 'RELATIONSHIP_STATUS_WIDOWED', // Góa
  RELATIONSHIP_STATUS_SEPARATED = 'RELATIONSHIP_STATUS_SEPARATED', // Ly thân
  RELATIONSHIP_STATUS_DIVORCED = 'RELATIONSHIP_STATUS_DIVORCED', // Ly hôn
  RELATIONSHIP_STATUS_HIDDEN = 'RELATIONSHIP_STATUS_HIDDEN',
  RELATIONSHIP_STATUS_CIVIL_PARTNERSHIP = 'RELATIONSHIP_STATUS_CIVIL_PARTNERSHIP',
}

export enum ResourceType {
  RESOURCE_TYPE_UNSPECIFIED = 'RESOURCE_TYPE_UNSPECIFIED',
  RESOURCE_TYPE_AVATAR = 'RESOURCE_TYPE_AVATAR',
  RESOURCE_TYPE_COVER = 'RESOURCE_TYPE_COVER',
  RESOURCE_TYPE_POST = 'RESOURCE_TYPE_POST',
  RESOURCE_TYPE_COMMENT = 'RESOURCE_TYPE_COMMENT',
  RESOURCE_TYPE_MESSAGE = 'RESOURCE_TYPE_MESSAGE',
  RESOURCE_TYPE_OTHER = 'RESOURCE_TYPE_OTHER',
}
