export enum ErrorMessage {
  SUCCESS = '00',
  UNHANDLED_ERROR = '1004',

  // auth
  VALIDATION_ERROR = '400',
  ACCESS_DENIED = '403',
  UNAUTHENTICATED = '401',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USERNAME_ALREADY_EXITS = 'USERNAME_ALREADY_EXITS',
  EMAIL_ALREADY_EXITS = 'EMAIL_ALREADY_EXITS',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID',
  PASSWORD_NEW_CANNOT_BE_SAME_AS_OLD = 'PASSWORD_NEW_CANNOT_BE_SAME_AS_OLD',
  PERMISSION_ALREADY_EXITS = 'PERMISSION_ALREADY_EXITS',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  ROLE_ALREADY_EXITS = 'ROLE_ALREADY_EXITS',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  IMPORT_EXCEL_ERROR = 'IMPORT_EXCEL_ERROR',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_INVALID = 'EMAIL_INVALID',

  // file
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',

  // profile
  USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
  FRIEND_REQUEST_ALREADY_SENT = 'FRIEND_REQUEST_ALREADY_SENT',

  // notification
  SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR',
  VERIFY_EMAIL_TOKEN_ERROR = 'VERIFY_EMAIL_TOKEN_ERROR',
  EMAIL_TOKEN_INVALID = 'EMAIL_TOKEN_INVALID',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  EMAIL_TOKEN_EXPIRED = 'EMAIL_TOKEN_EXPIRED',
  EMAIL_TOKEN_ALREADY_SENT = 'EMAIL_TOKEN_ALREADY_SENT',
  EMAIL_TOKEN_NOT_FOUND = 'EMAIL_TOKEN_NOT_FOUND',
  FORGET_PASSWORD_OTP_ALREADY_SENT = 'FORGET_PASSWORD_OTP_ALREADY_SENT',
  FORGET_PASSWORD_OTP_NOT_SENT_OR_EXPIRED = 'FORGET_PASSWORD_OTP_NOT_SENT_OR_EXPIRED',
  FORGET_PASSWORD_OTP_INVALID = 'FORGET_PASSWORD_OTP_INVALID',
}
